#!/bin/sh

set -e

USAGE="usage: bootstrap [-fh]\n\t-f\tforce rebuild\n\t-p\treinstall packages\n\t-h\tprint help"

while getopts fph flag
do
  case $flag in
    f) force=1 ;;
    p) packages=1 ;;
    \? | h) echo -e "$USAGE"; exit 1 ;;
  esac
done

neat_dir="$HOME/.local/neat"
repos_dir="$neat_dir/repos"
autobuilds_dir="$neat_dir/autobuilds"

repo="$repos_dir/emacs"
build="$autobuilds_dir/emacs"
prefix="$HOME/.local"

# Clone repository if does not exist
mkdir -p "$repos_dir"
[ ! -d "$repo" ] && git clone --recursive git://git.savannah.gnu.org/emacs.git "$repo"

# cd "$repo"
# git pull

# Copy repository to autobuilds
mkdir -p "$autobuilds_dir"
if [ ! -d "$build" ] || [ ! -z "$force" ]; then
  rm -rf "$build"
  cp -r "$repo" "$build"

  # Preparing to build
  # TODO: test dependencies:
  #       json - libjasson-dev or something
  #       png - libpng-dev
  #       rsvg - librsvg-dev
  cd "$build"
  # git checkout emacs-28.1.90

  # Remove misc junk
  mv lisp/play/morse.el lisp/play/cookie1.el .
  rm -rf lisp/play/*
  mv morse.el cookie1.el lisp/play
  # TODO:
  #   Probably should remove various languages' support
  #   like khmer.el{,c} and others

  ./autogen.sh
  mkdir -p build


  # --without-all \
  # Building
  cd build
  ../configure \
    --prefix="$prefix" \
    --with-json \
    --with-mailutils \
    --with-native-compilation \
    --with-pgtk \
    --with-png \
    --with-rsvg \
    --with-sound=no \
    --with-tiff \
    --with-xml2 \
    --without-compress-install \
    --without-m17n-flt \
    --without-gpm \
    --without-libotf
  make -j"$(nproc)"

  # TODO: testing

  # Installing
  mkdir -p "$prefix"
  make install
fi


# Install packages
[ -d "$HOME/.emacs.d" ] && rm -rf "$HOME/.emacs.d"

if [ "$packages" ] || [ ! -d "$HOME/.config/emacs" ];
then
  cd "$HOME/.config" # TODO: XDG
  rm -rf emacs
  git clone https://github.com/arealhero/emacs.git
  cd emacs
  emacs --batch -l init.el
fi

